web/router.ex
defmodule Buh.Router do
  use Buh.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Buh do
    pipe_through :browser # Use the default browser stack

    get  "/", PageController, :index
    post "/message", MessageController, :create
    get  "/articles", ArticleController, :index
    get  "/articles/:title", ArticleController, :show
  end

  scope "/" do
    if Mix.env == :dev do
      forward "/sent_emails", Bamboo.EmailPreviewPlug
    end
  end
end

lib/buh/emails.ex
defmodule Buh.Email do
  import Bamboo.Email

  def message(from, body) do
    new_email
    |> to("info@buhuchet38.ru")
    |> from("no-reply@buhuchet38.ru")
    |> subject("onsite-message")
    |> text_body("FROM: #{from}\nMESSAGE: #{body}")
  end
end

lib/buh/endpoint.ex
defmodule Buh.Endpoint do
  use Phoenix.Endpoint, otp_app: :buh

  socket "/socket", Buh.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :buh, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_buh_key",
    signing_salt: "ywONskyE"

  plug Buh.Router
end

lib/buh/mailer.ex
defmodule Buh.Mailer do
  use Bamboo.Mailer, otp_app: :buh
end

web/controllers/article_controller.ex
defmodule Buh.ArticleController do
  use Buh.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def show(conn, %{"title" => title}) do
    render conn, title
  end
end

web/controllers/message_controller.ex
defmodule Buh.MessageController do
  use Buh.Web, :controller

  def create(conn, %{"email" => email, "message" => message}) do
    if validate_email(email) do
      Buh.Email.message(email, message) |> Buh.Mailer.deliver_later
      conn
      |> put_flash(:info, "Ваше сообщение было отправлено, мы свяжемся с вами в ближайшее время.")
      |> redirect(to: page_path(conn, :index))
    else
      conn
      |> put_flash(:error, "Неверный email")
      |> redirect(to: page_path(conn, :index) <> "#message")
      |> halt
    end
  end

  defp validate_email(email), do: email =~ ~r/@/
end

web/controllers/page_controller.ex
defmodule Buh.PageController do
  use Buh.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/article_view.ex
defmodule Buh.ArticleView do
  use Buh.Web, :view
end

web/views/error_view.ex
defmodule Buh.ErrorView do
  use Buh.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Buh.LayoutView do
  use Buh.Web, :view

  def home_page?(Buh.PageView, "index.html"), do: true
  def home_page?(_, _), do: false
end

web/views/page_view.ex
defmodule Buh.PageView do
  use Buh.Web, :view

  def csrf_form_tag() do
    ~E"""
    <input name="_csrf_token" type="hidden" value="<%= get_csrf_token() %>">
    """
  end
end

web/templates/article/benefits.html.eex
<article class="center bg-light-gray bb b--light-silver pb5" id="articles">
  <h2 class="f1-ns f2 dib w-100 tc dark-gray mt5 pv3 mb0 pb0">Выгоды бухгалтерского аутсорсинга для малого бизнеса.</h2>
  <div class="mw8 services center mt3 ph4">
<p class="lh-copy f7 black-70 pb1">
  Не занимайтесь бумажной работой, занимайтесь бизнесом!
  Каждый предприниматель стремится достигать поставленных целей с минимальными издержками и получением максимальной прибыли. Увеличить эффективность малого бизнеса проще и выгоднее с помощью передачи бухгалтерии и налогового учета нашей организации.
  Выгода в 99 % случаев из 100%.
</p>

<p class="lh-copy f7 black-70 pb1">
  Чаще всего индивидуальные предприниматели и юридические лица обращаются к специализированным организациям за помощью и консультациями по следующим причинам:
  <ol class="black-80">
   <li> отсутствие собственного штатного сотрудника,</li>
   <li> необходимость экономии ресурсов.</li>
  </ol>
</p>

<p class="lh-copy f7 black-70 pb1">
  Оплата услуг и организация рабочего места штатного сотрудника требует значительных затрат (аренда, оснащение и т.д.), зачастую совершенно неподъемных для малого и среднего бизнеса. Услуги специализированной организации будут стоить гораздо меньше и охватывать более широкий круг вопросов и проблем, следовательно, сделают бизнес более эффективным.
  <ol start="3" class="black-80">
    <li>
      увольнение штатного сотрудника,
    </li>
    <li>
      столкновение с проблемами и контролирующими органами.
    </li>
  </ol>
</p>

<p class="lh-copy f7 black-70 pb1">
<p class="lh-copy f7 black-70 pb1">
    Третья и четвертая причины чаще всего взаимосвязаны – как только возникают проблемы или обнаруживаются ошибки в учете, ваш бухгалтер увольняется, оставляя вас под гнетом ответственности и нерешенных проблем. Профессиональная бухгалтерская организация сможет найти нетрадиционные решения проблем и отстоять их в споре с налоговыми органами и в суде.
    Начало бизнеса
    Начинающие предприниматели чаще всего становятся клиентами аутсорсеров, так как зачастую не имеют офиса и сотрудников. Они получают возможность не только консультироваться по всем вопросам регистрации и ведения бизнеса, но и снимают со своих плеч заботы по поиску, обучению штатного специалиста, обустройству его рабочего места, ведению учета, уплате налогов и т.д.
    Не оставайтесь с проблемами один на один 
    В сегодняшнее нестабильное время законодательные нормы меняются регулярно, вызывая у владельцев бизнеса массу вопросов и необходимость перестраивать бизнес-процессы организации. В связи с этим стала общепринятой практика обращения за консультациями и передача части учета организации сторонним консультантам.
    Даже если у вас есть штатный бухгалтер или юрист, порой он не в силах охватить весь пласт законодательных изменений и адекватно и быстро отреагировать на возникшие проблемы. А в бизнесе промедление смерти подобно. В нашей организации тщательно следят за повышением квалификации своих сотрудников, кроме того, характер их работы позволяет им ежечасно решать тысячи самых разносторонних задач, которые штатному сотруднику даже не снились.
    Не обладая знаниями в области налогового права, компании и частные лица иногда совершают действия, которые могут квалифицироваться как налоговые правонарушения, и даже, как уклонение от уплаты налогов и сборов. Не рискуйте своим успехом - если у вас появляются вопросы, всегда лучше проконсультироваться с независимыми экспертами. Это простое действие сэкономит ваши время и нервы.
  </p>
<p class="lh-copy f7 black-70 pb1">
    Вы сами определяете объем услуг для передачи на аутсорсинг: весь учет, кадровые вопросы, учет отдельных операций, экспертизу проектов, сдачу отчетности, налогообложение или же консультирование по отдельным проблемам или областям законодательства.
    В рамках консультационной деятельности наша организация не только решает проблемы организации и ведут ее учет, но и занимаются оптимизацией и оценкой целесообразности принятых решений, предупреждением отрицательных последствий и т.д. Управление налоговыми рисками позволяет сегодня сделать бизнес не только более устойчивым, но и более прибыльным.
    Правда, на практике к услугам сторонних налоговых консультантов компании прибегают только когда проблемы уже появились, и произошло столкновение с контролирующими органами. Поэтому наш перечень аутсорсинговых услуг постоянно расширяется. В него входит даже представительство интересов заказчика в суде, рассмотрение и ответ на претензии, общение с контролирующими органами.
  </p>
<p class="lh-copy f7 black-70 pb1">
  Специалисты нашей налоговой консультации готовы взять на себя весь ваш бухгалтерский и кадровый учет, а также: регистрацию/перерегистрацию, оптимизацию налогообложения, сдачу отчетности, обслуживанию ККТ. Мы даже предлагаем нашим клиентам услугу – экстренная помощь бухгалтеру, как раз для ситуаций, когда помощь Вам нужна срочно. Более 50 наших постоянных клиентов уже убедились в том, что мы работаем быстро, качественно и по доступным ценам.
  Все под контролем 
  Мы назначить уполномоченных сотрудников с нашей стороны, которые будут отвечать за управление процессом взаимодействия до подписания договора. Также утвердим схему бизнес-процессов и документооборота, дабы избежать потери времени на выяснения в процессе работы. Например, от вас могут потребоваться надлежащим образом оформленные первичные документы, а от нашей компании – их сохранность.
  Подпишите дополнительное соглашение о конфиденциальности и включите в него важные для вас моменты, в частности, утвердите правила хранения переданных исполнителю документов и предотвращения утечки коммерческой информации.
  Обратите внимание на положения договора об ответственности сторон: всю ответственность за ваш документооборот, учет и ошибки в нем на период сотрудничества будет нести наша организация. Кроме того, наша организация несет ответственность и после окончания действия договора по всем выполненным работам и оформленным документам. 
  Если бухгалтерия отнимает у вас много времени, не стоит самому разбираться с новшествами законодательства. 
  Помните: время – деньги. Наша консультация поможет вам сберечь и то, и другое.
</p>
</p>
<div class="sharethis-inline-share-buttons"></div>
</div>
</article>

web/templates/article/index.html.eex
<article class="center bg-light-gray bb b--light-silver pb5" id="articles">
  <h2 class="f1-ns f2 dib w-100 tc dark-gray mt5 pv3 mb0 pb0">Полезные статьи</h2>
  <div class="mw8 services center mt3">
    <div class="pa4 lh-copy">
      <ul>
        <li>
          <%= link "Выгоды бухгалтерского аутсорсинга для малого бизнеса", to: article_path(@conn, :show, "benefits.html"), class: "f4 fw6 db black link hover-purple" %> </li>
      </ul>
    </div>
  </div>
</article>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta property="og:image" content="http://buhuchet38.ru/images/accounting.jpeg"/>
        <meta property="og:title" content="БухУчет 38"/>
        <meta property="og:description" content="Бухгалтерские услуги в г. Иркутск"/>

        <title>Бухучет38</title>
        <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
        <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58edcdea17d2e20012e39b5d&product=inline-share-buttons"></script>
    </head>

    <body>
        <header class="sans-serif">
            <div class="cover bg-left bg-center-l" style="background-image: url(/images/accounting.jpeg)">
                <div class="bg-black-60 pb3 pb4-m pb5-l">
                    <nav class="dt w-100 center f6 fw6 ttu tracked">
                        <div class="tr bg-black-60 fixed w-100 ph3 pv3 pv4-ns ph4-m ph5-l" id="fixed-menu" data-scroll-header>
                          <%= if home_page?(@view_module, @view_template) do %>
                            <a class="link dim white dib mr0 mr3-ns mb3 mb0-ns mb3-m" href="#services" data-scroll >Цены и услуги</a>
                            <a class="link dim white dib mr3 mb3 mb0-ns" href="#fields"data-scroll>Сферы деятельности</a>
                            <a class="link dim white dib mr0 mr3-ns mr0-m" href="#contact" data-scroll>Контакты</a>
                            <a class="link dim white dib tc" href="#message" data-scroll>Напишите нам</a>
                          <% else %>
                            <a class="link dim white dib mr3 mb3 mb0-ns" href="/">Главная</a>
                            <a class="link dim white dib mr0 mr0-ns mr0-m" href="/articles" data-scroll>Статьи</a>
                          <% end %>
                        </div>
                    </nav>
                    <div class="tc-l mt6 ph3">
                        <%= if flash = get_flash(@conn, :info) do %>
                            <div class="flex items-center justify-center pa4 bg-lightest-blue navy">
                                <svg class="w1" data-icon="info" viewBox="0 0 32 32" style="fill:currentcolor">
                                    <title>info icon</title>
                                    <path d="M16 0 A16 16 0 0 1 16 32 A16 16 0 0 1 16 0 M19 15 L13 15 L13 26 L19 26 z M16 6 A3 3 0 0 0 16 12 A3 3 0 0 0 16 6"></path>
                                </svg>
                                <span class="lh-title ml3"><%= flash %></span>
                            </div>
                        <% end %>
                        <h1 class="f2 f1-l fw2 white-90 mb0 lh-title">Бухгалтерские услуги от компании БухУчет38</h1>
                        <h2 class="fw1 f3 white-80 mt3 mb4">Предоставляем налоговые консультации и бухгалтерские услуги для Вас и Вашей компании</h2>
                    </div>
                </div>
            </div> 
        </header>
        <main role="main">
            <%= render @view_module, @view_template, assigns %>
        </main>
        <footer class="bg-light-gray black-80 pv5 pv6-l ph4">
            <div class="wrapper mw8 center">
                <p class="f6"><span class="dib mr4 mr5-ns">©2017 БухУчет38</span>
                    <a class="link black-80 hover-green" href="#">info@buhuchet38.ru </a>/
                    <span class=""> +7 902 767 49 01 </span>
                </p>
            </div>
        </footer>
        <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    </body>
</html>

web/templates/page/index.html.eex
<article class="center bg-light-gray bb b--light-silver pb5" id="services">
    <h2 class="f1-ns f2 dib w-100 tc dark-gray mt5 pv3 mb0 pb0"> Цены и услуги </h2>
    <div class="mw8 services center mt3">
        <div class="cf ph2-ns cl">
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                  <a href="/articles">
                    <div class="tc">
                        <h1 class="f4">Полезные статьи</h1>
                    </div>
                  </a>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns h-25">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Регистрация</h1>
                        <hr class="mw3 bb bw1 b--black-10">
                    </div>
                    <p class="lh-copy center tc f7 black-70 pb1">
                        ООО, ИП, ДНТ, ТСЖ
                    </p>
                    <!-- <p class="center tc f2 black-90 ma0 pb2">
                        3000 ₽
                    </p> -->
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns h-25">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Внесение изменений</h1>
                        <hr class="mw3 bb bw1 b--black-10">
                    </div>
                    <p class="lh-copy center tc f7 black-70 pb1">
                        ООО, ИП, ДНТ, ТСЖ
                    </p>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Ликвидация </h1>
                        <hr class="mw3 bb bw1 b--black-10">
                    </div>
                    <p class="lh-copy center tc f7 black-70 pb1">
                        ООО, ИП, ДНТ, ТСЖ
                    </p>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns cl">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Ведение бухгалтерского и налогового учета</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Восстановление бухгалтерского и налогового учета</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Составление первичных документов</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Сдача нулевой отчетности и отчетности по вашим данным</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns cl">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Кадровый учет</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Консультации по ведению бухгалтерского учета</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Проведение инвентаризаций</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Калькуляция и сметы</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns cl">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Он-лайн доступ к базе 1С</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Консультации по автоматизации Вашего бизнеса</h1>
                    </div>
                </div>
            </div>
            <div class="fl w-100 w-25-ns ph4 pv1 pa1-ns">
                <div class="shadow-4 bg-animate hover-bg-washed-blue bg-white br3 pa2 mv3 ba b--black-10">
                    <div class="tc">
                        <h1 class="f4">Оптимизация бизнес-процессов </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
<article class="cf ph3 ph5-ns pv5 center bb b--light-silver" id="fields">
    <div class="center mw8">
        <header class="fn fl-ns w-50-ns pr4-ns pb4 tc tl-ns">
            <h1 class="mb3 mt0 lh-title">Сферы деятельности</h1>
        </header>
        <div class="fn fl-ns w-50-ns">
            <ul class="list pl0">
                <li class="pa3 pa4-ns pt0 pt0-ns bb b--black-10">
                    <b class="db f3 mb1">Торговля (оптовая, розничная)</b>
                </li>
                <li class="pa3 pa4-ns bb b--black-10">
                    <b class="db f3 mb1">
            Общественное питание
                    </b>
                    <!-- <span class="f5 db lh-copy measure">
                        The part of lowercase letters (such as k, b, and d) that ascends above the
                        x-height of the other lowercase letters in a face.
                    </span> -->
                </li>
                <li class="pa3 pa4-ns bb b--black-10">
                    <b class="db f3 mb1">
            Производство
                    </b>
                </li>
                <li class="pa3 pa4-ns bb b--black-10">
                    <b class="db f3 mb1">
            Услуги
                    </b>
                </li>
                <li class="pa3 pa4-ns bb b--black-10">
                    <b class="db f3 mb1">
            Внешнеэкономическая деятельность
                    </b>
                </li>
                <li class="pa3 pa4-ns bb b--black-10">
                    <b class="db f3 mb1">
            ЖКХ
                    </b>
                </li>
                <li class="pa3 pa4-ns bb b--black-10">
                    <b class="db f3 mb1">
            Строительство
                    </b>
                </li>
                <li class="pa3 pa4-ns">
                    <b class="db f3 mb1">
            Электронная коммерция
                    </b>
                </li>
            </ul>
        </div>
    </div>
</article>
<article class="center bg-light-gray bb b--light-silver pb4" id="contact">
    <h2 class="f1-ns f2 dib w-100 tc dark-gray mt5 pv3 mb0 pb0">Контакты и адрес</h2>
    <div id="map-wrapper" class="mt3 pv4 center mw8 cf">
        <div id="map" class="fl w-100 w-50-ns">
            <a href="https://yandex.ru/maps/?um=constructor%3AVBwkHl9-MLdvGvQr8P5rfit2kdJTcjuE&amp;source=constructorStatic" target="_blank"><img src="https://api-maps.yandex.ru/services/constructor/1.0/static/?sid=VBwkHl9-MLdvGvQr8P5rfit2kdJTcjuE&amp;width=500&amp;height=450&amp;lang=ru_RU&amp;sourceType=constructor" alt="" style="border: 0;" /></a>
        </div>
        <div id="contacts" class="tc fl w-100 w-50-ns pt4 pt0-ns">
            <div id="address" class="">
                <h3> Адрес </h3>
                <p>  поселок Ново-Иркутский, Магистральная 11А</p>
            </div>
            <div id="phone" class="mt4">
                <h3> Телефон </h3>
                <p> +7 902 767 49 01 </p>
            </div>
            <div id="email" class="mt4">
                <h3>E-mail</h3>
                <p> info@buhuchet38.ru </p>
            </div>
        </div>
    </div>
</article>
<article class="pb4 bb b--light-silver" id="message">
    <h2 class="f1 dib w-100 tc dark-gray mt5 pv3 mb0 pb0">Оставьте нам сообщение</h2>
    <div class="mt3 mw8 center">
        <form class="black-80" action="/message" method="post">
            <%= csrf_form_tag %>
            <div class="mw7 center">
                    <%= if flash = get_flash(@conn, :error) do %>
                        <span class="red mv2 ph2"> <%= flash %> </span>
                    <% end %>
                <div class="mt3 ph2">
                    <label class="f6 b db mb2" for="email-address">Email адрес</label>
                    <input class="db border-box hover-black w-100 ba b--black-20 pa2 br2 mb2" type="email" name="email"  id="email-address">
                </div>
                <div class="mt3 ph2" >
                    <label for="comment" class="f6 b db mb2">Сообщение</label>
                    <textarea style="min-height: 150px;" name="message" class="db border-box hover-black w-100 ba b--black-20 pa2 br2 mb2"></textarea>
                </div>
                <div class="mt3 tr ph2"><input class="b ph3 pv2 input-reset ba b--gray bg-transparent grow pointer f6" type="submit" value="Отправить"></div>

            </div>
        </form>
    </div>
</article>